sns/config/routes.rb
Rails.application.routes.draw do

  get 'user_index/show'

  # get 'users/show'
  devise_for :users
  root to: 'homes#top'
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]

  end
  resources :users, only: [:show, :edit, :update, :index]
  resources :user_index, only: [:show]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sns/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sns/app/models/favorite.rb
class Favorite < ApplicationRecord

 belongs_to :user
 belongs_to :post_image
end

sns/app/models/post_comment.rb
class PostComment < ApplicationRecord

belongs_to :user
belongs_to :post_image

end

sns/app/models/post_image.rb
class PostImage < ApplicationRecord

  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

sns/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :post_images,  dependent: :destroy
         has_many :post_comments,  dependent: :destroy
         has_many :favorites, dependent: :destroy

          attachment :profile_image
end

sns/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!,expect: [:top]
before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  post_images_path
end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

sns/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  def create
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.build(post_image_id: params[:post_image_id])
    favorite.save
    # redirect_to blogs_path
  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    favorite = Favorite.find_by(post_image_id: params[:post_image_id], user_id: current_user.id)
    favorite.destroy
    # redirect_to blogs_path
  end

private
  def post_image_params
    params.require(:post_image).permit(:title, :image, :caption )
  end

end

sns/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end
end

sns/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)  end

  def destroy
    PostComment.find_by(id: params[:id],post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

sns/app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new

  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end

  end

  def index
    @post_images = PostImage.page(params[:page]).reverse_order
    
   

  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to posy_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:title, :image, :caption )
  end
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

sns/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)  
  end

  private

  def user_params
    params.require(:user).permit(:name, :user_name, :profile_image, :introduction)
  end

end

sns/app/helpers/application_helper.rb
module ApplicationHelper
end

sns/app/helpers/favorites_helper.rb
module FavoritesHelper
end

sns/app/helpers/homes_helper.rb
module HomesHelper
end

sns/app/helpers/likes_helper.rb
module LikesHelper
end

sns/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

sns/app/helpers/post_images_helper.rb
module PostImagesHelper
end

sns/app/helpers/user_index_helper.rb
module UserIndexHelper
end

sns/app/helpers/users_helper.rb
module UsersHelper
end

sns/app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>

  <% if post_image.favorited_by?(current_user) %>
    <%= link_to post_image_favorites_path(post_image.id), method: :delete, remote: true do %>
     🤍<%= post_image.favorites.count %>いいね
    <% end %>
  <% else %>
    <%= link_to post_image_favorites_path(post_image.id), method: :post, remote: true do %>
      🖤<%= post_image.favorites.count %>いいね
    <% end %>
  <% end %>

<% else %>
    <%= post_image.favorites.count %>
<% end %>

sns/app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @post_image.id %>').html("<%= j(render partial: 'favolites/favolite', locals: {post_image: @post_image}) %>");

sns/app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @post_image.id %>').html("<%= j(render partial: 'favolites/favolite', locals: {post_image: @post_image}) %>");

sns/app/views/homes/top.html.erb
top page

sns/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sns</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <script src="https://kit.fontawesome.com/f1ea8cd658.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-12　 bg-dark">
    <li>
       <%= link_to '一覧', post_images_path ,class:" text-light" %>
     </li>

     <% if user_signed_in? %>
     <li>
       <%= link_to '投稿フォーム', new_post_image_path ,class:" text-light" %>
     </li>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path,class:" text-light", method: :delete %>
      </li>
      <li>
      <%= link_to 'マイページ', user_path(current_user.id), class:" text-light" %>
      </li>
    <% else %>
      
      <li>
        <%= link_to "新規登録", new_user_registration_path, class:" text-light" %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path, class:" text-light" %>
      </li>
    <% end %>
    </div>
    <%= yield %>
  </body>
</html>

sns/app/views/post_images/index.html.erb
<div class='list-container py-5 bg-dark text-light'>
<div class="w-50 mx-auto mt-4">


<% @post_images.each do |post_image| %>
 <div class="row">
  <div class="col-2">
   <%= attachment_image_tag post_image.user, :profile_image, :fill, 35, 35, format: 'jpeg', class:"my-3 rounded-circle " %>
  </div>
  <div class="col-10 my-auto ">
   <%= link_to user_path(post_image.user.id) ,class:"text-light" do %>
   @<%= post_image.user.name %>
   <% end %>
  </div>  
 </div>
 
 <div class="row-12">
  <%= link_to user_path(post_image.user.id) do %>
   <%= attachment_image_tag post_image, :image, :fill, 500 , 500 ,class:"card-img-top"%>
  <% end %>
 </div>
 <div class="row-12 mt-3">

  <div id="favorites_buttons_<%= post_image.id %>">
   <%= render partial: 'favorites/favorite', locals: { post_image: post_image} %>
  </div>
     

    <p><i class="fas fa-star pr-2"></i><i class="far fa-star pr-2"></i>
    <%= link_to  post_image_path(post_image.id) ,class:"text-light" do %><i class="far fa-comment-dots pr-2"></i>
     <% end %>
    <i class="far fa-paper-plane"></i></p>

   <div class="row-12 mb-4">

    <p><%= post_image.caption %></p>
    <p><%= link_to "コメント#{post_image.post_comments.count} 件をすべて見る", post_image_path(post_image.id), class:"text-light" %></p>
    <p><%= post_image.created_at.strftime('%m/%d/%H') %></p>
   </div>
<% end %>

  </div>
 </div>
</div>

sns/app/views/post_images/new.html.erb
<%= form_with model: @post_image, local:true do |f| %>
<h1>新規投稿</h1>

<% if @post_image.errors.any? %>
  <%= @post_image.errors.count %>件のエラーが発生しました
  <% @post_image.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h4><%= f.submit 'シェア'%></h4>
<h4><%= f.attachment_field :image %></>

  <h4>キャプションを書く</h4>
  <%= f.text_area :caption %>

<% end %>

sns/app/views/post_images/show.html.erb
<div class="comments">
<p>コメント件数：<%= @post_image.post_comments.count %></p>
<% @post_image.post_comments.each do |post_comment| %>

  <%= post_comment.comment %>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %>
  <% if post_comment.user == current_user %>
  <div class="comment-delete">
    <%= link_to post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete do %>
    <p>削除</p>
    <% end %>
  <% end %>
  </div>

  
  <% end %>

</div>

<div class="new-comment">

  <%= form_with(model:[@post_image,@post_comment], local: true) do |f| %>

    <%= f.text_area :comment, rows:'5',placeholder: "#{current_user.name}としてコメントを追加..." %>
    <%= f.submit "投稿する" %>

  <% end %>
</div>

sns/app/views/users/edit.html.erb
<%= form_with model:@user, local:true do |f| %>
<h4>キャンセル</h4>
<h2>プロフィールを編集</h2>
  <%= f.submit "変更を保存" %>

  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60%>
   <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <label for="inputImage">プロフィール写真を変更</label>

  <label for="inputName">名前</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputName">ユーザーネーム</label>
  <%= f.text_field :user_name, autofocus: true, id:"inputName", placeholder:"ユーザーネーム"%>


  <label for="inputName">自己紹介</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介"%>





<% end %>

sns/app/views/users/show.html.erb
<div class="profile-container-12">
  <div class="row">

  <h3><%= @user.user_name %></h3>
   <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, format: 'jpeg' %>
  <p><%= @post_images.count %>投稿</p>
  <p>フォロワー</p>
  <p>フォロー中</p>
  <h5><%= @user.name %></h5>
  <p><%= @user.introduction %></p>
   <% if @user.id == current_user.id %>
   <%= link_to "プロフィールを編集", edit_user_path(@user) %>
   <%= link_to "保存", edit_user_path(@user) %>
   <% else %>
   <%= link_to "フォロー中", edit_user_path(@user) %>
   <%= link_to "メッセージ", edit_user_path(@user) %>
   <%= link_to "メール", edit_user_path(@user) %>

   <% end %>



<% @post_images.each do |post_image| %>
<div>
  <%= link_to post_images_path do %>
    <%= attachment_image_tag post_image, :image, :fill, 300 , 300 %>
  <% end %>

<% end %>
<%= paginate @post_images %>
</div>
</div>